version: "3.9"

services:
  housing-api:
    #image: housing-api:latest  # ✅ Use the pre-built image
    image: docker.io/sumanth12345678/housing-api
    container_name: housing-api
    ports:
      - "8000:8000"
    #restart: always
    volumes:
      - ./logs:/app/logs
    environment:
      - ENV=production
    networks:
      - housing-network
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - housing-network

networks:
  housing-network:
    external: true
